<?php

namespace Database\Seeders\Catalogos;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Datos de catálogo de `tc_subcategorias_refacciones` (80 filas, réplica exacta del entorno de referencia).
 * Generado automáticamente — no editar a mano: regenerar desde la fuente si cambia.
 */
class SubcategoriasRefaccionesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tc_subcategorias_refacciones')->truncate();

        $rows = [
            ['id_subcategoria_refaccion' => 1, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Juntas y Empaques de Motor', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 2, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Soportes de Motor', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 3, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Bandas y Correas', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 4, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Poleas y Tensores', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 5, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Bomba de Aceite', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 6, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Pistones y Anillos', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 7, 'id_categoria_refaccion' => 1, 's_subcategoria_refaccion' => 'Metales de Biela y Bancada', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 8, 'id_categoria_refaccion' => 2, 's_subcategoria_refaccion' => 'Bujías', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 9, 'id_categoria_refaccion' => 2, 's_subcategoria_refaccion' => 'Bobinas de Ignición', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 10, 'id_categoria_refaccion' => 2, 's_subcategoria_refaccion' => 'Cables de Bujías', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 11, 'id_categoria_refaccion' => 2, 's_subcategoria_refaccion' => 'Módulos de Encendido', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 12, 'id_categoria_refaccion' => 3, 's_subcategoria_refaccion' => 'Filtros de Aceite', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/1200x/f1/99/f6/f199f69a4ec2e3b9d911037dd25e052a.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 13, 'id_categoria_refaccion' => 3, 's_subcategoria_refaccion' => 'Filtros de Aire', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/736x/17/21/d9/1721d9f0bfdd92785bef82ffb987aac9.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 14, 'id_categoria_refaccion' => 3, 's_subcategoria_refaccion' => 'Filtros de Combustible', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/1200x/e9/9d/7f/e99d7fb3a622d46d02725303f2b1ecf2.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 15, 'id_categoria_refaccion' => 3, 's_subcategoria_refaccion' => 'Filtros de Cabina', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/1200x/79/a8/f3/79a8f3a934a1975d821912cc4b040861.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 16, 'id_categoria_refaccion' => 4, 's_subcategoria_refaccion' => 'Balatas (Pastillas de Freno)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 17, 'id_categoria_refaccion' => 4, 's_subcategoria_refaccion' => 'Discos de Freno', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 18, 'id_categoria_refaccion' => 4, 's_subcategoria_refaccion' => 'Tambores de Freno', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 19, 'id_categoria_refaccion' => 4, 's_subcategoria_refaccion' => 'Cilindros de Rueda (Bombas de Freno)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 20, 'id_categoria_refaccion' => 4, 's_subcategoria_refaccion' => 'Calipers (Mordazas)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 21, 'id_categoria_refaccion' => 4, 's_subcategoria_refaccion' => 'Mangueras y Líneas de Freno', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 22, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Amortiguadores y Struts', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 23, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Horquillas y Brazos de Control', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 24, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Terminales de Dirección (Interiores y Exteriores)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 25, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Bieletas (Tornillos Estabilizadores)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 26, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Resortes', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 27, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Cajas y Cremalleras de Dirección', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 28, 'id_categoria_refaccion' => 5, 's_subcategoria_refaccion' => 'Bujes de Suspensión', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 29, 'id_categoria_refaccion' => 6, 's_subcategoria_refaccion' => 'Kit de Embrague (Clutch)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 30, 'id_categoria_refaccion' => 6, 's_subcategoria_refaccion' => 'Volante Motriz', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 31, 'id_categoria_refaccion' => 6, 's_subcategoria_refaccion' => 'Juntas Homocinéticas (Flechas)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 32, 'id_categoria_refaccion' => 6, 's_subcategoria_refaccion' => 'Soportes de Transmisión', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 33, 'id_categoria_refaccion' => 6, 's_subcategoria_refaccion' => 'Filtro de Transmisión Automática', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 34, 'id_categoria_refaccion' => 6, 's_subcategoria_refaccion' => 'Cilindro Maestro y Esclavo de Embrague', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 35, 'id_categoria_refaccion' => 7, 's_subcategoria_refaccion' => 'Radiadores', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 36, 'id_categoria_refaccion' => 7, 's_subcategoria_refaccion' => 'Bombas de Agua', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 37, 'id_categoria_refaccion' => 7, 's_subcategoria_refaccion' => 'Termostatos', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 38, 'id_categoria_refaccion' => 7, 's_subcategoria_refaccion' => 'Mangueras de Radiador', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 39, 'id_categoria_refaccion' => 7, 's_subcategoria_refaccion' => 'Depósitos de Anticongelante', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 40, 'id_categoria_refaccion' => 7, 's_subcategoria_refaccion' => 'Ventiladores y Fan Clutch', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 41, 'id_categoria_refaccion' => 8, 's_subcategoria_refaccion' => 'Baterías', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 42, 'id_categoria_refaccion' => 8, 's_subcategoria_refaccion' => 'Alternadores', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 43, 'id_categoria_refaccion' => 8, 's_subcategoria_refaccion' => 'Motores de Arranque (Marchas)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 44, 'id_categoria_refaccion' => 8, 's_subcategoria_refaccion' => 'Switches e Interruptores', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 45, 'id_categoria_refaccion' => 8, 's_subcategoria_refaccion' => 'Relevadores (Relays)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 46, 'id_categoria_refaccion' => 9, 's_subcategoria_refaccion' => 'Convertidores Catalíticos', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 47, 'id_categoria_refaccion' => 9, 's_subcategoria_refaccion' => 'Silenciadores (Mofles)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 48, 'id_categoria_refaccion' => 9, 's_subcategoria_refaccion' => 'Tubos de Escape', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 49, 'id_categoria_refaccion' => 9, 's_subcategoria_refaccion' => 'Juntas de Escape', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 50, 'id_categoria_refaccion' => 10, 's_subcategoria_refaccion' => 'Faros Delanteros', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 51, 'id_categoria_refaccion' => 10, 's_subcategoria_refaccion' => 'Calaveras (Luces Traseras)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 52, 'id_categoria_refaccion' => 10, 's_subcategoria_refaccion' => 'Luces de Niebla', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 53, 'id_categoria_refaccion' => 10, 's_subcategoria_refaccion' => 'Focos y Bulbos', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 54, 'id_categoria_refaccion' => 10, 's_subcategoria_refaccion' => 'Direccionales e Intermitentes', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 55, 'id_categoria_refaccion' => 11, 's_subcategoria_refaccion' => 'Facias (Parachoques)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 56, 'id_categoria_refaccion' => 11, 's_subcategoria_refaccion' => 'Salpicaderas (Guardafangos)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 57, 'id_categoria_refaccion' => 11, 's_subcategoria_refaccion' => 'Espejos Laterales', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 58, 'id_categoria_refaccion' => 11, 's_subcategoria_refaccion' => 'Parrillas', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 59, 'id_categoria_refaccion' => 11, 's_subcategoria_refaccion' => 'Manijas de Puerta', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 60, 'id_categoria_refaccion' => 11, 's_subcategoria_refaccion' => 'Amortiguadores de Cofre y Cajuela', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 61, 'id_categoria_refaccion' => 12, 's_subcategoria_refaccion' => 'Sensores de Oxígeno', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 62, 'id_categoria_refaccion' => 12, 's_subcategoria_refaccion' => 'Sensor MAF (Flujo de Aire)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 63, 'id_categoria_refaccion' => 12, 's_subcategoria_refaccion' => 'Sensor MAP (Presión Absoluta)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 64, 'id_categoria_refaccion' => 12, 's_subcategoria_refaccion' => 'Sensor CKP (Posición de Cigüeñal)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 65, 'id_categoria_refaccion' => 12, 's_subcategoria_refaccion' => 'Sensor CMP (Posición de Árbol de Levas)', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 66, 'id_categoria_refaccion' => 12, 's_subcategoria_refaccion' => 'Sensores de Rueda ABS', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 67, 'id_categoria_refaccion' => 13, 's_subcategoria_refaccion' => 'Aceite de Motor', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 68, 'id_categoria_refaccion' => 13, 's_subcategoria_refaccion' => 'Anticongelante y Refrigerante', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 69, 'id_categoria_refaccion' => 13, 's_subcategoria_refaccion' => 'Líquido de Frenos', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 70, 'id_categoria_refaccion' => 13, 's_subcategoria_refaccion' => 'Aceite de Transmisión', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 71, 'id_categoria_refaccion' => 13, 's_subcategoria_refaccion' => 'Aditivos', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 72, 'id_categoria_refaccion' => 14, 's_subcategoria_refaccion' => 'Compresores de A/C', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 73, 'id_categoria_refaccion' => 14, 's_subcategoria_refaccion' => 'Condensadores de A/C', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 74, 'id_categoria_refaccion' => 14, 's_subcategoria_refaccion' => 'Evaporadores de A/C', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 75, 'id_categoria_refaccion' => 14, 's_subcategoria_refaccion' => 'Válvulas de Expansión', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 76, 'id_categoria_refaccion' => 14, 's_subcategoria_refaccion' => 'Filtros Deshidratadores', 's_img_subcategoria_refaccion' => 'https://costerautomotive.com/cdn/shop/articles/autopartes-mexico.png?v=1732326249&width=840', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 77, 'id_categoria_refaccion' => 15, 's_subcategoria_refaccion' => 'Llantas', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/736x/0a/6e/b4/0a6eb45c6b06b084284b9a50f1a39c6c.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 78, 'id_categoria_refaccion' => 15, 's_subcategoria_refaccion' => 'Rines de Acero', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/736x/dd/8e/1f/dd8e1f59a4fc0be117163be001c76f0c.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 79, 'id_categoria_refaccion' => 15, 's_subcategoria_refaccion' => 'Rines de Aluminio', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/1200x/35/74/ee/3574ee43043d7b8879b6ea2ffa63206c.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
            ['id_subcategoria_refaccion' => 80, 'id_categoria_refaccion' => 15, 's_subcategoria_refaccion' => 'Birlos y Tuercas de Seguridad', 's_img_subcategoria_refaccion' => 'https://i.pinimg.com/1200x/b6/98/ff/b698ff8fe59e43576dc32b8871c19a5c.jpg', 'b_activo' => 1, 'created_at' => null, 'updated_at' => null],
        ];

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('tc_subcategorias_refacciones')->insert($chunk);
        }
    }
}
